### ISSUE TITLE
希望可以新增一个升级选项

### ISSUE THREAD

**Issue by backrunner** [passeway/Snell#2]
有一些Server使用这个脚本安装了低版本的Snell，希望有一个选项可以不修改配置，直接原地升级Server

**Comment by passeway** [comment]
> 有一些Server使用这个脚本安装了低版本的Snell，希望有一个选项可以不修改配置，直接原地升级Server

关于升级问题，我的建议是卸载后重新安装，因为新升级的服务端配置新增DNS配置。
